#!/bin/bash
set -e

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo "Build images."
docker build $options -t sometheycallme/docker-splunk .

echo "Show image sizes."
docker images | egrep '^splunk\b' | sort

echo
echo "WARN: you should docker tag the docker-splunk image."
echo
