#!/bin/bash
set -ex -o pipefail

echo "Step1: Test for basic splunk install"
docker run -t -i --entrypoint bash sometheycallme/docker-splunk -c "ls -l /opt"

docker rm -f splunkd || :
docker run -d --name splunkd -p 8000:8000 sometheycallme/docker-splunk

